export enum UserPermissions {
  USER_ADD = 'USER_ADD',
  USER_GET = 'USER_GET',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  USER_UPDATE_ROLES = 'USER_UPDATE_ROLES',

  ORGANIZATION_ADD = 'ORGANIZATION_ADD',
  ORGANIZATION_GET = 'ORGANIZATION_GET',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  // ORGANIZATION_DELETE = 'ORGANIZATION_DELETE'

  ORGANIZATION_ASSOCIATION = 'ORGANIZATION_ASSOCIATION',

  ORGANIZATION_RATE_POLICIES_CREATE = 'ORGANIZATION_RATE_POLICIES_CREATE',
  ORGANIZATION_RATE_POLICIES_GET = 'ORGANIZATION_RATE_POLICIES_GET',
  ORGANIZATION_RATE_POLICIES_UPDATE = 'ORGANIZATION_RATE_POLICIES_UPDATE',
}
